version: "3.3"

services:
  signal_alerts_cli:
    deploy:
      replicas: "${REPLICAS:-1}"    
    image: "${IMAGE:-docker_logger:latest}"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    build:
      context: ..
      dockerfile: docker_logger/Dockerfile
      args:
        user: "${MATRIX_USER}"
        host: "${MATRIX_HOST}"
        password: "${MATRIX_PASSWORD}"
