services:
  - docker

jobs:
  include:
    - stage: test
    - script:
          - make docker_mormo_test
      name: integration test
    - script:
          - curl -fsSL https://goss.rocks/install | sudo sh
          - sudo curl -L https://raw.githubusercontent.com/aelsabbahy/goss/master/extras/dcgoss/dcgoss -o /usr/local/bin/dcgoss
          - sudo chmod +x /usr/local/bin/dcgoss
          - env MORMO_IMAGE=joeystevens00/mormo:$TRAVIS_BRANCH-api dcgoss run app
      name: goss test
