version: "3.3"

services:
  signal_alerts_cli:
    depends_on: [redis]
    environment:
      - MESSAGE_QUEUE=http://message_queue:9000
      - REDIS_HOST=redis
    hostname: "${HOSTNAME:-signal_alerts_cli}"
    image: "${IMAGE:-signal_alerts:cli}"
    restart: always
    build:
      context: ..
      dockerfile: cli/Dockerfile
      args:
        user: "${MATRIX_USER}"
        host: "${MATRIX_HOST}"
        file: "${ALERTS_FILE:-alerts.yaml}"
        password: "${MATRIX_PASSWORD}"
        glassnode_api_key: "${GLASSNODE_API_KEY}"
  redis:
    image: redis
