version: "3.3"

services:
  signal_alerts_cli:
    depends_on: [queue]
    environment:
      - MESSAGE_QUEUE=http://queue:9000
      - REDIS_HOST=redis
    image: "${IMAGE:-signal_alerts:cli}"
    restart: always
    build:
      context: ..
      dockerfile: cli/Dockerfile
      args:
        user: "${MATRIX_USER}"
        host: "${MATRIX_HOST}"
        file: "${ALERTS_FILE:-alerts.yaml}"
        password: "${MATRIX_PASSWORD}"
        glassnode_api_key: "${GLASSNODE_API_KEY}"
  redis:
    image: redis
  queue:
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    deploy:
      replicas: "${REPLICAS:-1}"
      endpoint_mode: dnsrr
    image: "${IMAGE:-server_alerts:message_queue}"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    build:
      context: ..
      dockerfile: log_queue/Dockerfile
      args:
        user: "${MATRIX_USER}"
        host: "${MATRIX_HOST}"
        password: "${MATRIX_PASSWORD}"
