version: "3.3"

services:
  signal_alerts_cli:
    depends_on: [message_queue]
    environment:
      - MESSAGE_QUEUE=message_queue:9000    
    hostname: "${HOSTNAME:-signal_alerts_cli}"
    image: "${IMAGE:-signal_alerts:cli}"
    restart: always
    volumes:
      - "signaldata:/tmp/data:rw"
    build:
      context: ..
      dockerfile: cli/Dockerfile
      args:
        user: "${MATRIX_USER}"
        host: "${MATRIX_HOST}"
        file: "${ALERTS_FILE:-alerts.yaml}"
        password: "${MATRIX_PASSWORD}"
        datadir: /tmp/data
        glassnode_api_key: "${GLASSNODE_API_KEY}"

volumes:
  signaldata:
    external:
      name: signaldata
