version: "3.3"

services:
  signal_alerts_api:
    depends_on:
      - redis
      - message_queue
    image: "${IMAGE:-signal_alerts:api}"
    restart: always
    build:
      context: ..
      dockerfile: api/Dockerfile
      args:
        glassnode_api_key: "${GLASSNODE_API_KEY}"
    environment:
      - REDIS_HOST=redis
    ports:
      - 8000:8000
  redis:
    image: redis
  message_queue:
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    deploy:
      replicas: "${REPLICAS:-1}"
    image: "${IMAGE:-server_alerts:message_queue}"
    restart: always
    build:
      context: ..
      dockerfile: log_queue/Dockerfile
      args:
        user: "${MATRIX_USER}"
        host: "${MATRIX_HOST}"
        password: "${MATRIX_PASSWORD}"
