version: "3.3"

services:
  signal_alerts_api:
    hostname: "${HOSTNAME:-signal_alerts_api}"
    depends_on:
      - redis
    image: "${IMAGE:-signal_alerts:api}"
    restart: always
    build:
      context: ..
      dockerfile: api/Dockerfile
      args:
        glassnode_api_key: "${GLASSNODE_API_KEY}"
    environment:
      - REDIS_HOST=redis
    ports:
      - 8000:8000
  redis:
    image: redis
