version: "3.3"

services:
  app:
    depends_on:
      - redis
    image: signal_alerts:api
    restart: always
    volumes:
      - "signaldata:/tmp/data:rw"
    build:
      context: ..
      dockerfile: api/Dockerfile
      args:
        glassnode_api_key: "${GLASSNODE_API_KEY}"
    environment:
      - REDIS_HOST=redis
    ports:
      - 8000:8000
  redis:
    image: redis

volumes:
  signaldata:
    external:
      name: signaldata
