version: "3.3"

services:
  server_alerts:
    depends_on: [redis]
    environment:
      - MESSAGE_QUEUE=http://message_queue:9000
      - REDIS_HOST=redis
    deploy:
      replicas: "${REPLICAS:-1}"
    image: "${IMAGE:-server_alerts:latest}"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    build:
      context: ..
      dockerfile: server_alerts/Dockerfile
      args:
        file: "${ALERTS_FILE:-server_alerts.yaml}"
        user: "${MATRIX_USER}"
        host: "${MATRIX_HOST}"
        password: "${MATRIX_PASSWORD}"
        docker_hostnames: 1
  redis:
    image: redis
  message_queue:
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    deploy:
      replicas: "${REPLICAS:-1}"
    image: "${IMAGE:-server_alerts:message_queue}"
    restart: always
    build:
      context: ..
      dockerfile: log_queue/Dockerfile
      args:
        user: "${MATRIX_USER}"
        host: "${MATRIX_HOST}"
        password: "${MATRIX_PASSWORD}"
