version: "3.3"

services:
  server_alerts:
    depends_on: [message_queue]
    environment:
      - MESSAGE_QUEUE=message_queue:9000
    deploy:
      replicas: "${REPLICAS:-1}"
    image: "${IMAGE:-server_alerts:latest}"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    build:
      context: ..
      dockerfile: server_alerts/Dockerfile
      args:
        file: "${ALERTS_FILE:-server_alerts.yaml}"
        user: "${MATRIX_USER}"
        host: "${MATRIX_HOST}"
        password: "${MATRIX_PASSWORD}"
        docker_hostnames: 1
